export {default as Hotel} from './Hotel'
export {default as Booking} from './Booking'
export {default as Esthetic} from './Esthetic'
export {default as Hospital} from './Hospital'
export {default as Spa} from './Spa'
export {default as RouterService} from './module'