import { RouterInterface } from "./type";
import Layout from "../components/Layout/Layout";
import Home from "../pages/Home/Home";
import Store from "../pages/Store/Store";
import NotFound from "../pages/NotFound";
import { Spa, Hospital, Esthetic, Booking, Hotel } from "../modules/Service";
import Intro from "../pages/Introduce/Intro";
import Blog from "../pages/Blog/Blog";

const RouterView: RouterInterface[] = [
  {
    path: "/",
    public: true,
    name: "Layout",
    element: () => <Layout />,
    children: [
      {
        name: "Homepage",
        path: "",
        index: true,
        public: true,
        children: [],
        element: () => <Home />,
      },
      {
        name: "ThuCung",
        index: false,
        path: "thucung",
        public: true,
        element: () => <Store />,
        children: [
          {
            name: "ChoCanh",
            index: false,
            path: "chocanh",
            children: [],
            public: true,
            element: () => <Store />,
          },
          {
            name: "MeoCanh",
            index: false,
            path: "meocanh",
            children: [],
            public: true,
            element: () => <Store />,
          },
          {
            name: "ThuKieng",
            index: false,
            path: "thukieng",
            children: [],
            public: true,
            element: () => <Store />,
          },
          {
            name: "Hamster",
            index: false,
            path: "hamster",
            children: [],
            public: true,
            element: () => <Store />,
          },
          {
            name: "ThuCungKhac",
            children: [],
            index: false,
            path: "thucungkhac",
            public: true,
            element: () => <Store />,
          },
        ],
      },
      {
        name: "ThucAnThuCung",
        index: false,
        path: "thucanthucung",
        public: true,
        element: () => <Store />,
        children: [
          {
            name: "ThucAnChoCho",
            children: [],
            index: false,
            path: "ta_cho",
            public: true,
            element: () => <Store />,
          },
          {
            name: "ThucAnChoMeo",
            children: [],
            index: false,
            path: "ta_meo",
            public: true,
            element: () => <Store />,
          },
          {
            name: "ThucAnKhac",
            index: false,
            path: "ta_khac",
            children: [],
            public: true,
            element: () => <Store />,
          },
        ],
      },
      {
        name: "VatDungThuCung",
        index: false,
        children: [],
        path: "vatdungthucung",
        public: true,
        element: () => <Store />,
      },
      {
        name: "PhuKienThuCung",
        index: false,
        path: "phukienthucung",
        children: [],
        public: true,
        element: () => <Store />,
      },
      {
        name: "DoChoiThuCung",
        index: false,
        path: "dochoithucung",
        children: [],
        public: true,
        element: () => <Store />,
      },
      {
        name: "DichVu",
        index: false,
        path: "dichvu",
        public: true,
        element: () => <Store />,
        children: [
          {
            name: "CatTia",
            index: false,
            path: "cattia",
            children: [],
            public: true,
            element: () => <Esthetic />,
          },
          {
            name: "TrongGiu",
            index: false,
            path: "tronggiu",
            children: [],
            public: true,
            element: () => <Hotel />,
          },
          {
            name: "Spa",
            index: false,
            path: "spa",
            children: [],
            public: true,
            element: () => <Spa />,
          },
          {
            name: "BenhVien",
            index: false,
            children: [],
            path: "benhvienthuy",
            public: true,
            element: () => <Hospital />,
          },
          {
            name: "SanPhamThuY",
            children: [],
            index: false,
            path: "sanphamthuy",
            public: true,
            element: () => <Hospital />,
          },
          {
            name: "ChiaSe",
            children: [],
            index: false,
            path: "chiase",
            public: true,
            element: () => <Booking />,
          },
          {
            name: "DatHen",
            index: false,
            path: "dathen",
            children: [],
            public: true,
            element: () => <Booking />,
          },
        ],
      },
      {
        name: "TapChi",
        index: false,
        path: "tapchi",
        children: [],
        public: true,
        element: () => <Blog />,
      },
      {
        name: "GioiThieu",
        index: false,
        path: "gioithieu",
        children: [],
        public: true,
        element: () => <Intro />,
      },
    ],
  },
  {
    path: "*",
    public: true,
    name: "NotFound",
    children: [],
    element: () => <NotFound />,
  },
];

export default RouterView;
